[package]
name = "conway-game-of-life"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.25.0"
egui-macroquad = { git = "https://github.com/optozorax/egui-macroquad.git" }
macroquad = "0.4.4"

